# Generated by Django 5.1.6 on 2025-09-22 13:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='exam',
            old_name='exam_date',
            new_name='start_date',
        ),
        migrations.DeleteModel(
            name='EventDates',
        ),
    ]
