# Generated by Django 5.1.6 on 2025-09-23 05:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0002_rename_exam_date_exam_start_date_delete_eventdates'),
        ('region', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('last_name', models.CharField(max_length=255)),
                ('first_name', models.CharField(max_length=255)),
                ('middle_name', models.CharField(max_length=255)),
                ('test_day', models.CharField(blank=True, max_length=20, null=True)),
                ('e_date', models.DateField(blank=True, null=True)),
                ('e_time', models.CharField(blank=True, max_length=8, null=True)),
                ('sm', models.IntegerField(default=0)),
                ('imei', models.CharField(max_length=14)),
                ('group', models.PositiveSmallIntegerField(default=0)),
                ('seat', models.PositiveSmallIntegerField(default=0)),
                ('embedding', models.TextField(blank=True, null=True)),
                ('img_b64', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_hand_checking', models.BooleanField(default=False)),
                ('is_entered', models.BooleanField(default=False)),
                ('subject_id', models.IntegerField(blank=True, null=True)),
                ('subject_name', models.CharField(blank=True, max_length=255, null=True)),
                ('lang_id', models.IntegerField(blank=True, null=True)),
                ('level_id', models.IntegerField(blank=True, null=True)),
                ('phone', models.CharField(blank=True, max_length=13, null=True)),
                ('ps_ser', models.CharField(blank=True, max_length=5, null=True)),
                ('ps_number', models.CharField(blank=True, max_length=10, null=True)),
                ('exam', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='exam.test')),
                ('region', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='region.region')),
            ],
            options={
                'verbose_name': 'Student',
                'verbose_name_plural': 'Students',
                'db_table': 'student',
            },
        ),
        migrations.CreateModel(
            name='EntryLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('first_image', models.TextField(blank=True, null=True)),
                ('last_image', models.TextField(blank=True, null=True)),
                ('accuracy', models.PositiveSmallIntegerField(default=0)),
                ('max_accuracy', models.PositiveSmallIntegerField(default=0)),
                ('first_enter_time', models.DateTimeField(blank=True, null=True)),
                ('last_enter_time', models.DateTimeField(blank=True, null=True)),
                ('is_hand_checking', models.BooleanField(default=False)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='exam.student')),
            ],
            options={
                'verbose_name': 'EntryLog',
                'verbose_name_plural': 'EntryLogs',
                'db_table': 'entry_log',
            },
        ),
    ]
