# Generated by Django 5.1.6 on 2025-09-23 05:42

import pgvector.django.vector
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0003_student_entrylog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='embedding',
            field=pgvector.django.vector.VectorField(blank=True, dimensions=512, null=True),
        ),
    ]
