# Generated by Django 5.1.6 on 2025-09-23 11:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0004_alter_student_embedding'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='exam',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='exam.exam'),
        ),
    ]
