# Generated by Django 5.1.6 on 2025-09-24 07:45

import pgvector.django.vector
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0005_alter_student_exam'),
        ('region', '0002_rename_type_ipcamera_cam_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='embedding',
            field=pgvector.django.vector.VectorField(blank=True, db_index=True, dimensions=512, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='imei',
            field=models.CharField(db_index=True, max_length=14),
        ),
        migrations.AddIndex(
            model_name='student',
            index=models.Index(fields=['imei', 'embedding'], name='student_imei_eba60a_idx'),
        ),
    ]
