# Generated by Django 5.1.6 on 2025-09-24 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0006_alter_student_embedding_alter_student_imei_and_more'),
        ('region', '0002_rename_type_ipcamera_cam_type_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='student',
            name='student_imei_eba60a_idx',
        ),
        migrations.AddIndex(
            model_name='student',
            index=models.Index(fields=['imei'], name='student_imei_76ce97_idx'),
        ),
    ]
