# Generated by Django 5.1.6 on 2025-09-24 07:46

import pgvector.django.vector
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0007_remove_student_student_imei_eba60a_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='embedding',
            field=pgvector.django.vector.VectorField(blank=True, dimensions=512, null=True),
        ),
    ]
