# Generated by Django 5.1.6 on 2025-09-24 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0008_alter_student_embedding'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='is_hand_checking',
        ),
        migrations.AddField(
            model_name='student',
            name='is_face',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='student',
            name='is_image',
            field=models.BooleanField(default=True),
        ),
    ]
