# Generated by Django 5.1.6 on 2025-11-05 12:00

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AccessEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('event_type', models.CharField(choices=[('remote_verification', 'Remote Verification Request'), ('access_event', 'Access Event'), ('door_status', 'Door Status Change'), ('alarm_event', 'Alarm Event'), ('unknown', 'Unknown')], db_index=True, max_length=50)),
                ('format_type', models.CharField(default='xml', max_length=20)),
                ('major', models.CharField(blank=True, max_length=10, null=True)),
                ('minor', models.CharField(blank=True, max_length=10, null=True)),
                ('employee_no', models.CharField(blank=True, max_length=100, null=True)),
                ('name', models.CharField(blank=True, max_length=200, null=True)),
                ('card_no', models.CharField(blank=True, max_length=100, null=True)),
                ('door_name', models.CharField(blank=True, max_length=200, null=True)),
                ('door_no', models.CharField(blank=True, max_length=50, null=True)),
                ('device_name', models.CharField(blank=True, max_length=200, null=True)),
                ('serial_no', models.CharField(blank=True, max_length=100, null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('picture_url', models.URLField(blank=True, max_length=500, null=True)),
                ('verification_method', models.CharField(blank=True, max_length=100, null=True)),
                ('direction', models.CharField(choices=[('entry', 'Entry'), ('exit', 'Exit'), ('unknown', 'Unknown')], default='unknown', max_length=20)),
                ('attendance_status', models.CharField(blank=True, max_length=10, null=True)),
                ('request_id', models.CharField(blank=True, db_index=True, max_length=100, null=True)),
                ('requires_action', models.BooleanField(db_index=True, default=False)),
                ('raw_data', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Access Event',
                'verbose_name_plural': 'Access Events',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['-timestamp', 'event_type'], name='access_cont_timesta_0607ae_idx'), models.Index(fields=['requires_action', '-timestamp'], name='access_cont_require_79f2b7_idx')],
            },
        ),
        migrations.CreateModel(
            name='VerificationRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_id', models.CharField(db_index=True, max_length=100, unique=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('denied', 'Denied'), ('expired', 'Expired')], db_index=True, default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_by', models.CharField(blank=True, max_length=100, null=True)),
                ('reason', models.TextField(blank=True, null=True)),
                ('event', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='verification', to='access_control.accessevent')),
            ],
            options={
                'verbose_name': 'Verification Request',
                'verbose_name_plural': 'Verification Requests',
                'ordering': ['-created_at'],
            },
        ),
    ]
