# Generated by Django 5.1.6 on 2025-11-12 06:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('access_control', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='verificationrequest',
            name='event',
        ),
        migrations.DeleteModel(
            name='AccessEvent',
        ),
        migrations.DeleteModel(
            name='VerificationRequest',
        ),
    ]
