# Generated by Django 5.1.6 on 2025-11-12 07:09

import django.db.models.deletion
import pgvector.django.vector
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('access_control', '0002_remove_verificationrequest_event_delete_accessevent_and_more'),
        ('region', '0005_delete_monitorpc'),
    ]

    operations = [
        migrations.CreateModel(
            name='NormalUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Familiya')),
                ('first_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Ism')),
                ('middle_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Sharif')),
                ('imei', models.CharField(db_index=True, max_length=14, unique=True, verbose_name='Pinfl')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktiv')),
                ('img_b64', models.TextField(blank=True, null=True, verbose_name='Rasm')),
                ('img_vector', pgvector.django.vector.VectorField(blank=True, dimensions=512, null=True, verbose_name='Vector')),
                ('zone', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='region.zone', verbose_name='Bino')),
            ],
        ),
    ]
