# Generated by Django 5.1.6 on 2025-11-12 08:03

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('access_control', '0003_initial'),
        ('exam', '0016_alter_studentlog_status'),
        ('region', '0005_delete_monitorpc'),
    ]

    operations = [
        migrations.CreateModel(
            name='StaffRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=20, verbose_name='Nomi')),
                ('code', models.CharField(max_length=20, verbose_name='Kod')),
                ('status', models.BooleanField(db_index=True, default=True, verbose_name='Status')),
            ],
            options={
                'verbose_name': 'Rol',
                'verbose_name_plural': 'Rollar',
                'db_table': 'staff_role',
            },
        ),
        migrations.CreateModel(
            name='UserAttachExam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('imei', models.CharField(db_index=True, max_length=14, verbose_name='Pinfl')),
                ('access_datetime', models.DateTimeField()),
                ('expired_datetime', models.DateTimeField()),
                ('status', models.BooleanField(default=True, verbose_name='Aktiv')),
            ],
            options={
                'verbose_name': 'UserAttachExam',
                'verbose_name_plural': 'UserAttachExams',
                'db_table': 'user_attach_exam',
            },
        ),
        migrations.AlterModelOptions(
            name='normaluser',
            options={'verbose_name': 'NormalUser', 'verbose_name_plural': 'NormalUsers'},
        ),
        migrations.RenameField(
            model_name='normaluser',
            old_name='is_active',
            new_name='status',
        ),
        migrations.RemoveField(
            model_name='normaluser',
            name='zone',
        ),
        migrations.AddField(
            model_name='normaluser',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='normaluser',
            name='is_blacklist',
            field=models.BooleanField(default=False, verbose_name="Qora ro'yxatda bormi"),
        ),
        migrations.AddField(
            model_name='normaluser',
            name='phone',
            field=models.CharField(blank=True, max_length=13, null=True, verbose_name='Telefon'),
        ),
        migrations.AddField(
            model_name='normaluser',
            name='ps_num',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Nomer'),
        ),
        migrations.AddField(
            model_name='normaluser',
            name='ps_ser',
            field=models.CharField(blank=True, max_length=5, null=True, verbose_name='Seriya'),
        ),
        migrations.AddField(
            model_name='normaluser',
            name='region',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='region.region', verbose_name='Doimiy viloyat'),
        ),
        migrations.AddField(
            model_name='normaluser',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterModelTable(
            name='normaluser',
            table='normal_user',
        ),
        migrations.CreateModel(
            name='NormalUserLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('employee_no', models.CharField(blank=True, db_index=True, max_length=100, null=True, verbose_name='Student ID')),
                ('img_face', models.TextField(blank=True, null=True, verbose_name="O'tgandagi rasm")),
                ('door', models.PositiveSmallIntegerField(default=0, verbose_name='Kirdi|Chiqdi eshik')),
                ('pass_time', models.DateTimeField(blank=True, null=True, verbose_name="O'tgan vaqt")),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP address')),
                ('mac_address', models.CharField(blank=True, null=True, verbose_name='MAC address')),
                ('direction', models.CharField(choices=[('entry', 'Kirish'), ('exit', 'Chiqish'), ('unknown', "Noma'lum")], default='entry', max_length=20, verbose_name="Yo'nalish")),
                ('status', models.CharField(choices=[('approved', 'Tasdiqlangan'), ('denied', 'Rad etilgan'), ('not_open', 'Ochilmadi')], db_index=True, default='', max_length=20, verbose_name='Holat')),
                ('normal_user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='access_control.normaluser', verbose_name='Normal User')),
            ],
            options={
                'verbose_name': 'NormalUserLog',
                'verbose_name_plural': 'NormalUserLogs',
                'db_table': 'normal_user_log',
            },
        ),
        migrations.AddField(
            model_name='normaluser',
            name='role',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='access_control.staffrole', verbose_name='Rol'),
        ),
        migrations.AddIndex(
            model_name='normaluser',
            index=models.Index(fields=['imei'], name='normal_user_imei_1ee221_idx'),
        ),
        migrations.AddField(
            model_name='userattachexam',
            name='exam',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exam.exam', verbose_name='Exam'),
        ),
        migrations.AddField(
            model_name='userattachexam',
            name='normal_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='access_control.normaluser', verbose_name='Normal User'),
        ),
        migrations.AddField(
            model_name='userattachexam',
            name='zones',
            field=models.ManyToManyField(db_table='zones_user', related_name='user_zones', to='region.zone', verbose_name='Biriktirilgan binolar'),
        ),
        migrations.AddIndex(
            model_name='normaluserlog',
            index=models.Index(fields=['employee_no', '-pass_time'], name='normal_user_employe_d27625_idx'),
        ),
        migrations.AddIndex(
            model_name='userattachexam',
            index=models.Index(fields=['imei'], name='user_attach_imei_6fc296_idx'),
        ),
    ]
