# Generated by Django 5.1.6 on 2025-11-12 09:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('access_control', '0004_staffrole_userattachexam_alter_normaluser_options_and_more'),
        ('region', '0005_delete_monitorpc'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userattachexam',
            name='zones',
        ),
        migrations.AddField(
            model_name='userattachexam',
            name='zone',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_zone', to='region.zone', verbose_name='Biriktirilgan binolar'),
        ),
    ]
