# Generated by Django 5.1.6 on 2025-11-12 12:11

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('access_control', '0005_remove_userattachexam_zones_userattachexam_zone'),
    ]

    operations = [
        migrations.AddField(
            model_name='normaluser',
            name='access_datetime',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='normaluser',
            name='expired_datetime',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='UserAttachExam',
        ),
    ]
