# Generated by Django 5.1.6 on 2025-11-14 10:47

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('access_control', '0006_normaluser_access_datetime_and_more'),
        ('region', '0005_delete_monitorpc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='normaluser',
            name='access_datetime',
            field=models.DateTimeField(blank=True),
        ),
        migrations.AlterField(
            model_name='normaluser',
            name='expired_datetime',
            field=models.DateTimeField(blank=True),
        ),
        migrations.AlterField(
            model_name='normaluser',
            name='first_name',
            field=models.CharField(blank=True, max_length=255, verbose_name='Ism'),
        ),
        migrations.AlterField(
            model_name='normaluser',
            name='imei',
            field=models.CharField(blank=True, db_index=True, max_length=14, unique=True, validators=[django.core.validators.RegexValidator('^\\d{14}$', 'PINFL 14 ta raqamdan iborat')], verbose_name='PINFL'),
        ),
        migrations.AlterField(
            model_name='normaluser',
            name='last_name',
            field=models.CharField(blank=True, max_length=255, verbose_name='Familiya'),
        ),
        migrations.AlterField(
            model_name='normaluser',
            name='middle_name',
            field=models.CharField(blank=True, max_length=255, verbose_name='Sharif'),
        ),
        migrations.AlterField(
            model_name='normaluser',
            name='phone',
            field=models.CharField(blank=True, max_length=13, null=True, validators=[django.core.validators.RegexValidator(message="Telefon raqam: '+998901234567' formatida bo'lishi kerak", regex='^\\+998\\d{9}$')], verbose_name='Telefon'),
        ),
        migrations.AlterField(
            model_name='normaluser',
            name='ps_num',
            field=models.CharField(max_length=7, validators=[django.core.validators.RegexValidator('^\\d{7}$', 'Faqat 7 ta raqam')], verbose_name='Nomer'),
        ),
        migrations.AlterField(
            model_name='normaluser',
            name='ps_ser',
            field=models.CharField(max_length=2, validators=[django.core.validators.RegexValidator('^[A-Z]{2}$', 'Faqat 2 ta lotin harfi')], verbose_name='Seriya'),
        ),
        migrations.AlterField(
            model_name='normaluser',
            name='region',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='region.region', verbose_name='Doimiy viloyat'),
        ),
        migrations.AlterField(
            model_name='normaluser',
            name='role',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='access_control.staffrole', verbose_name='Rol'),
        ),
        migrations.AlterUniqueTogether(
            name='normaluser',
            unique_together={('ps_ser', 'ps_num')},
        ),
    ]
