# Generated by Django 5.1.6 on 2025-11-14 11:54

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('access_control', '0007_alter_normaluser_access_datetime_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='normaluser',
            name='gender',
            field=models.CharField(choices=[('M', 'Erkak'), ('F', 'Ayol')], default='M', max_length=1, verbose_name='Jinsi'),
        ),
        migrations.AlterField(
            model_name='normaluser',
            name='imei',
            field=models.CharField(db_index=True, max_length=14, unique=True, validators=[django.core.validators.RegexValidator('^\\d{14}$', 'PINFL 14 ta raqamdan iborat')], verbose_name='PINFL'),
        ),
    ]
