# Generated by Django 5.1.6 on 2025-11-14 14:57

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('access_control', '0008_normaluser_gender_alter_normaluser_imei'),
    ]

    operations = [
        migrations.AlterField(
            model_name='normaluser',
            name='phone',
            field=models.CharField(blank=True, max_length=13, null=True, validators=[django.core.validators.RegexValidator(message="Telefon raqam: '+998901234567' formatida bo'lishi kerak", regex='^\\998\\d{9}$')], verbose_name='Telefon'),
        ),
    ]
