# Generated by Django 5.1.6 on 2025-11-17 10:29

import django.core.validators
import django.db.models.deletion
import pgvector.django.vector
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('access_control', '0009_alter_normaluser_phone'),
        ('exam', '0017_alter_studentlog_direction_alter_studentlog_status'),
        ('region', '0005_delete_monitorpc'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='normaluser',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='normaluser',
            name='region',
        ),
        migrations.RemoveField(
            model_name='normaluser',
            name='role',
        ),
        migrations.RemoveField(
            model_name='normaluserlog',
            name='normal_user',
        ),
        migrations.AlterModelOptions(
            name='normaluserlog',
            options={'verbose_name': 'Vakil va nazoratchi logi', 'verbose_name_plural': 'Vakil va nazoratchi loglari'},
        ),
        migrations.AddField(
            model_name='normaluserlog',
            name='normal_user_id',
            field=models.PositiveBigIntegerField(default=0, verbose_name='User ID'),
        ),
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('last_name', models.CharField(blank=True, max_length=255, verbose_name='Familiya')),
                ('first_name', models.CharField(blank=True, max_length=255, verbose_name='Ism')),
                ('middle_name', models.CharField(blank=True, max_length=255, verbose_name='Sharif')),
                ('imei', models.CharField(db_index=True, max_length=14, unique=True, validators=[django.core.validators.RegexValidator('^\\d{14}$', 'PINFL 14 ta raqamdan iborat')], verbose_name='PINFL')),
                ('ps_ser', models.CharField(max_length=2, validators=[django.core.validators.RegexValidator('^[A-Z]{2}$', 'Faqat 2 ta lotin harfi')], verbose_name='Seriya')),
                ('ps_num', models.CharField(max_length=7, validators=[django.core.validators.RegexValidator('^\\d{7}$', 'Faqat 7 ta raqam')], verbose_name='Nomer')),
                ('phone', models.CharField(blank=True, max_length=13, null=True, validators=[django.core.validators.RegexValidator(message="Telefon raqam: '+998901234567' formatida bo'lishi kerak", regex='^\\998\\d{9}$')], verbose_name='Telefon')),
                ('img_b64', models.TextField(blank=True, null=True, verbose_name='Rasm')),
                ('img_vector', pgvector.django.vector.VectorField(blank=True, dimensions=512, null=True, verbose_name='Vector')),
                ('gender', models.CharField(choices=[('M', 'Erkak'), ('F', 'Ayol')], default='M', max_length=1, verbose_name='Jinsi')),
                ('status', models.BooleanField(default=True, verbose_name='Aktiv')),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='region.region', verbose_name='Doimiy viloyat')),
            ],
            options={
                'verbose_name': 'Xodim',
                'verbose_name_plural': 'Xodimlar',
                'db_table': 'staff',
            },
        ),
        migrations.CreateModel(
            name='Supervisor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('last_name', models.CharField(blank=True, max_length=255, verbose_name='Familiya')),
                ('first_name', models.CharField(blank=True, max_length=255, verbose_name='Ism')),
                ('middle_name', models.CharField(blank=True, max_length=255, verbose_name='Sharif')),
                ('imei', models.CharField(db_index=True, max_length=14, unique=True, validators=[django.core.validators.RegexValidator('^\\d{14}$', 'PINFL 14 ta raqamdan iborat')], verbose_name='PINFL')),
                ('ps_ser', models.CharField(max_length=2, validators=[django.core.validators.RegexValidator('^[A-Z]{2}$', 'Faqat 2 ta lotin harfi')], verbose_name='Seriya')),
                ('ps_num', models.CharField(max_length=7, validators=[django.core.validators.RegexValidator('^\\d{7}$', 'Faqat 7 ta raqam')], verbose_name='Nomer')),
                ('phone', models.CharField(blank=True, max_length=13, null=True, validators=[django.core.validators.RegexValidator(message="Telefon raqam: '+998901234567' formatida bo'lishi kerak", regex='^\\998\\d{9}$')], verbose_name='Telefon')),
                ('img_b64', models.TextField(blank=True, null=True, verbose_name='Rasm')),
                ('img_vector', pgvector.django.vector.VectorField(blank=True, dimensions=512, null=True, verbose_name='Vector')),
                ('is_blacklist', models.BooleanField(default=False, verbose_name="Qora ro'yxatda bormi")),
                ('gender', models.CharField(choices=[('M', 'Erkak'), ('F', 'Ayol')], default='M', max_length=1, verbose_name='Jinsi')),
                ('status', models.BooleanField(default=True, verbose_name='Aktiv')),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='region.region', verbose_name='Doimiy viloyat')),
            ],
            options={
                'verbose_name': 'Nazoratchi',
                'verbose_name_plural': 'Nazoratchilar',
                'db_table': 'supervisor',
            },
        ),
        migrations.CreateModel(
            name='SupervisorExam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('imei', models.CharField(db_index=True, max_length=14, unique=True, validators=[django.core.validators.RegexValidator('^\\d{14}$', 'PINFL 14 ta raqamdan iborat')], verbose_name='PINFL')),
                ('n_type', models.CharField(choices=[('main', 'Asosiy'), ('reserve', 'Zaxira')], default='main', max_length=20, verbose_name='Tip')),
                ('sm', models.PositiveSmallIntegerField(default=0, verbose_name='Smena')),
                ('group_n', models.PositiveSmallIntegerField(default=0, verbose_name='Guruh')),
                ('test_date', models.DateField(blank=True, null=True, verbose_name='Test date')),
                ('access_datetime', models.DateTimeField(blank=True, verbose_name='Boshlanish vaqti')),
                ('expired_datetime', models.DateTimeField(blank=True, verbose_name='Tugash vaqti')),
                ('is_participated', models.BooleanField(default=False, verbose_name='Qatnashdimi')),
                ('exam', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='exam.exam', verbose_name='Tadbir')),
                ('supervisor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='access_control.supervisor', verbose_name='Nazoratchi')),
                ('zone', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='region.zone', verbose_name='Bino')),
            ],
            options={
                'verbose_name': 'Tadbir nazoratchi',
                'verbose_name_plural': 'Tadbir nazoratchilari',
                'db_table': 'supervisor_exam',
            },
        ),
        migrations.DeleteModel(
            name='StaffRole',
        ),
        migrations.DeleteModel(
            name='NormalUser',
        ),
        migrations.AddIndex(
            model_name='staff',
            index=models.Index(fields=['imei'], name='staff_imei_181f5a_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='staff',
            unique_together={('ps_ser', 'ps_num')},
        ),
        migrations.AddIndex(
            model_name='supervisor',
            index=models.Index(fields=['imei'], name='supervisor_imei_2dfc78_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='supervisor',
            unique_together={('ps_ser', 'ps_num')},
        ),
        migrations.AddIndex(
            model_name='supervisorexam',
            index=models.Index(fields=['imei'], name='supervisor__imei_df2171_idx'),
        ),
    ]
