# Generated by Django 5.1.6 on 2025-11-17 14:39

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('access_control', '0010_alter_normaluser_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff',
            name='phone',
            field=models.CharField(blank=True, max_length=12, null=True, validators=[django.core.validators.RegexValidator(message="Telefon raqam: '998901234567' formatida bo'lishi kerak", regex='^\\998\\d{9}$')], verbose_name='Telefon'),
        ),
        migrations.AlterField(
            model_name='supervisor',
            name='phone',
            field=models.CharField(blank=True, max_length=13, null=True, validators=[django.core.validators.RegexValidator(message="Telefon raqam: '998901234567' formatida bo'lishi kerak", regex='^\\998\\d{9}$')], verbose_name='Telefon'),
        ),
    ]
