# Generated by Django 5.1.6 on 2025-11-17 15:22

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('access_control', '0011_alter_staff_phone_alter_supervisor_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff',
            name='phone',
            field=models.CharField(blank=True, max_length=12, null=True, validators=[django.core.validators.RegexValidator(message="Telefon raqam: '998901234567' formatida bo'lishi kerak", regex='^998\\d{9}$')], verbose_name='Telefon'),
        ),
        migrations.AlterField(
            model_name='staff',
            name='ps_ser',
            field=models.CharField(max_length=2, validators=[django.core.validators.RegexValidator('^[A-Za-z]{2}$', 'Faqat 2 ta lotin harfi')], verbose_name='Seriya'),
        ),
        migrations.AlterField(
            model_name='supervisor',
            name='phone',
            field=models.CharField(blank=True, max_length=13, null=True, validators=[django.core.validators.RegexValidator(message="Telefon raqam: '998901234567' formatida bo'lishi kerak", regex='^998\\d{9}$')], verbose_name='Telefon'),
        ),
    ]
