# Generated by Django 5.1.6 on 2025-11-18 12:32

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('access_control', '0012_alter_staff_phone_alter_staff_ps_ser_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff',
            name='ps_ser',
            field=models.CharField(max_length=2, validators=[django.core.validators.RegexValidator('^[A-Za-z]{2}$', 'Faqat 2 ta katta lotin harfi')], verbose_name='Seriya'),
        ),
    ]
