# Generated by Django 5.1.6 on 2025-11-18 13:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('access_control', '0013_alter_staff_ps_ser'),
        ('region', '0005_delete_monitorpc'),
    ]

    operations = [
        migrations.AddField(
            model_name='normaluserlog',
            name='zone',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='region.zone', verbose_name='Bino'),
        ),
    ]
