# Generated by Django 5.1.6 on 2025-11-21 07:33

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('access_control', '0014_normaluserlog_zone'),
        ('exam', '0018_examzoneswingbar_created_at_and_more'),
        ('region', '0005_delete_monitorpc'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='supervisor',
            name='is_blacklist',
        ),
        migrations.RemoveField(
            model_name='supervisor',
            name='phone',
        ),
        migrations.RemoveField(
            model_name='supervisor',
            name='region',
        ),
        migrations.AddField(
            model_name='supervisor',
            name='access_datetime',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, verbose_name='Boshlanish vaqti'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='supervisor',
            name='exam',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='exam.exam', verbose_name='Tadbir'),
        ),
        migrations.AddField(
            model_name='supervisor',
            name='expired_datetime',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, verbose_name='Tugash vaqti'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='supervisor',
            name='group_n',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='Guruh'),
        ),
        migrations.AddField(
            model_name='supervisor',
            name='is_participated',
            field=models.BooleanField(default=False, verbose_name='Qatnashdimi'),
        ),
        migrations.AddField(
            model_name='supervisor',
            name='sm',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='Smena'),
        ),
        migrations.AddField(
            model_name='supervisor',
            name='test_date',
            field=models.DateField(blank=True, null=True, verbose_name='Test date'),
        ),
        migrations.AddField(
            model_name='supervisor',
            name='zone',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='region.zone', verbose_name='Bino'),
        ),
        migrations.DeleteModel(
            name='SupervisorExam',
        ),
    ]
