# Generated by Django 5.1.6 on 2025-11-21 10:10

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('access_control', '0015_remove_supervisor_is_blacklist_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='supervisor',
            name='category',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Tadbir'),
        ),
        migrations.AlterField(
            model_name='supervisor',
            name='imei',
            field=models.CharField(db_index=True, max_length=14, validators=[django.core.validators.RegexValidator('^\\d{14}$', 'PINFL 14 ta raqamdan iborat')], verbose_name='PINFL'),
        ),
    ]
