# Generated by Django 5.1.6 on 2025-11-21 10:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('access_control', '0016_supervisor_category_alter_supervisor_imei'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='supervisor',
            unique_together=set(),
        ),
    ]
