# Generated by Django 5.1.6 on 2025-11-21 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('access_control', '0017_alter_supervisor_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='normaluserlog',
            name='first_name',
            field=models.CharField(blank=True, max_length=255, verbose_name='Ism'),
        ),
        migrations.AddField(
            model_name='normaluserlog',
            name='last_name',
            field=models.CharField(blank=True, max_length=255, verbose_name='Familiya'),
        ),
        migrations.AddField(
            model_name='normaluserlog',
            name='middle_name',
            field=models.CharField(blank=True, max_length=255, verbose_name='Sharif'),
        ),
        migrations.AddField(
            model_name='normaluserlog',
            name='normal_user_type',
            field=models.CharField(choices=[('staff', 'Xodim'), ('supervisor', 'Nazoratchi'), ('unknown', "Noma'lum")], default='unknown', max_length=255, verbose_name='User turi'),
        ),
    ]
