# Generated by Django 5.1.6 on 2025-11-21 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('access_control', '0018_normaluserlog_first_name_normaluserlog_last_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supervisor',
            name='category',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Toifa'),
        ),
    ]
