# Generated by Django 5.1.6 on 2025-11-21 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('access_control', '0019_alter_supervisor_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='supervisor',
            name='category',
        ),
        migrations.AddField(
            model_name='supervisor',
            name='category_key',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Toifa kodi'),
        ),
        migrations.AddField(
            model_name='supervisor',
            name='category_name',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Toifa nomi'),
        ),
        migrations.AlterField(
            model_name='supervisor',
            name='first_name',
            field=models.CharField(blank=True, max_length=50, verbose_name='Ism'),
        ),
        migrations.AlterField(
            model_name='supervisor',
            name='is_participated',
            field=models.BooleanField(default=False, verbose_name='Davomat'),
        ),
        migrations.AlterField(
            model_name='supervisor',
            name='last_name',
            field=models.CharField(blank=True, max_length=50, verbose_name='Familiya'),
        ),
        migrations.AlterField(
            model_name='supervisor',
            name='middle_name',
            field=models.CharField(blank=True, max_length=50, verbose_name='Sharif'),
        ),
    ]
