# Generated by Django 5.1.6 on 2025-11-21 12:13

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('access_control', '0020_remove_supervisor_category_supervisor_category_key_and_more'),
        ('exam', '0018_examzoneswingbar_created_at_and_more'),
        ('region', '0005_delete_monitorpc'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventSupervisor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category_key', models.CharField(blank=True, max_length=10, null=True, verbose_name='Toifa kodi')),
                ('category_name', models.CharField(blank=True, max_length=50, null=True, verbose_name='Toifa nomi')),
                ('test_date', models.DateField(blank=True, null=True, verbose_name='Test date')),
                ('sm', models.PositiveSmallIntegerField(default=0, verbose_name='Smena')),
                ('group_n', models.PositiveSmallIntegerField(default=0, verbose_name='Guruh')),
                ('access_datetime', models.DateTimeField(blank=True, verbose_name='Boshlanish vaqti')),
                ('expired_datetime', models.DateTimeField(blank=True, verbose_name='Tugash vaqti')),
                ('is_participated', models.BooleanField(default=False, verbose_name='Davomat')),
            ],
            options={
                'verbose_name': 'Biriktirilgan nazoratchi',
                'verbose_name_plural': 'Biriktirilgan nazoratchilar',
                'db_table': 'event_supervisor',
            },
        ),
        migrations.RemoveIndex(
            model_name='supervisor',
            name='supervisor_imei_2dfc78_idx',
        ),
        migrations.RemoveField(
            model_name='supervisor',
            name='access_datetime',
        ),
        migrations.RemoveField(
            model_name='supervisor',
            name='category_key',
        ),
        migrations.RemoveField(
            model_name='supervisor',
            name='category_name',
        ),
        migrations.RemoveField(
            model_name='supervisor',
            name='exam',
        ),
        migrations.RemoveField(
            model_name='supervisor',
            name='expired_datetime',
        ),
        migrations.RemoveField(
            model_name='supervisor',
            name='group_n',
        ),
        migrations.RemoveField(
            model_name='supervisor',
            name='is_participated',
        ),
        migrations.RemoveField(
            model_name='supervisor',
            name='sm',
        ),
        migrations.RemoveField(
            model_name='supervisor',
            name='test_date',
        ),
        migrations.RemoveField(
            model_name='supervisor',
            name='zone',
        ),
        migrations.AddField(
            model_name='supervisor',
            name='region',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='region.region', verbose_name='Doimiy'),
        ),
        migrations.AlterField(
            model_name='supervisor',
            name='imei',
            field=models.CharField(db_index=True, max_length=14, unique=True, validators=[django.core.validators.RegexValidator('^\\d{14}$', 'PINFL 14 ta raqamdan iborat')], verbose_name='PINFL'),
        ),
        migrations.AddField(
            model_name='eventsupervisor',
            name='exam',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='exam.exam', verbose_name='Tadbir'),
        ),
        migrations.AddField(
            model_name='eventsupervisor',
            name='supervisor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='access_control.supervisor', verbose_name='Tadbir'),
        ),
        migrations.AddField(
            model_name='eventsupervisor',
            name='zone',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='region.zone', verbose_name='Bino'),
        ),
    ]
