# Generated by Django 5.1.6 on 2025-11-24 05:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('access_control', '0021_eventsupervisor_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventsupervisor',
            name='supervisor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='access_control.supervisor', verbose_name='Nazoratchi'),
        ),
    ]
