# Generated by Django 5.1.6 on 2025-11-24 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('access_control', '0022_alter_eventsupervisor_supervisor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventsupervisor',
            name='access_datetime',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Boshlanish vaqti'),
        ),
        migrations.AlterField(
            model_name='eventsupervisor',
            name='expired_datetime',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Tugash vaqti'),
        ),
    ]
