# Generated by Django 5.1.6 on 2025-11-24 13:33

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('access_control', '0023_alter_eventsupervisor_access_datetime_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventsupervisor',
            name='access_datetime',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Boshlanish vaqti'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='eventsupervisor',
            name='expired_datetime',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Tugash vaqti'),
            preserve_default=False,
        ),
    ]
