# Generated by Django 5.1.6 on 2025-11-26 05:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('access_control', '0024_alter_eventsupervisor_access_datetime_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='staff',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='staff',
            name='region',
        ),
        migrations.RemoveField(
            model_name='supervisor',
            name='region',
        ),
        migrations.DeleteModel(
            name='EventSupervisor',
        ),
        migrations.DeleteModel(
            name='Staff',
        ),
        migrations.DeleteModel(
            name='Supervisor',
        ),
    ]
