# Generated by Django 5.1.6 on 2025-09-23 06:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('region', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ipcamera',
            old_name='type',
            new_name='cam_type',
        ),
        migrations.RemoveField(
            model_name='ipcamera',
            name='last_active_time',
        ),
        migrations.RemoveField(
            model_name='ipcamera',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='ipcamera',
            name='location',
        ),
        migrations.RemoveField(
            model_name='ipcamera',
            name='longitude',
        ),
        migrations.RemoveField(
            model_name='ipcamera',
            name='onvif_url',
        ),
        migrations.AddField(
            model_name='ipcamera',
            name='zone',
            field=models.ForeignKey(help_text='Bino', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cameras', to='region.zone'),
        ),
        migrations.AlterField(
            model_name='ipcamera',
            name='mac_address',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
        migrations.CreateModel(
            name='Computer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('region_number', models.IntegerField(default=0)),
                ('name', models.CharField(max_length=255)),
                ('number', models.IntegerField(default=0)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('mac_address', models.CharField(blank=True, max_length=255, null=True, unique=True)),
                ('username', models.CharField(blank=True, max_length=255, null=True)),
                ('password', models.CharField(blank=True, max_length=255, null=True)),
                ('ip_camera', models.ForeignKey(help_text='Camera', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='computer_cameras', to='region.ipcamera')),
                ('zone', models.ForeignKey(help_text='Bino', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='computer_zones', to='region.zone')),
            ],
            options={
                'verbose_name': 'Computer',
                'verbose_name_plural': 'Computers',
                'db_table': 'computer',
            },
        ),
    ]
