# Generated by Django 5.1.6 on 2025-09-26 07:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0009_remove_student_is_hand_checking_student_is_face_and_more'),
        ('face', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GenerateFaceExam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_generated', models.BooleanField(default=False)),
                ('exam', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='exam.exam')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
