# Generated by Django 5.1.6 on 2025-11-26 05:14

import django.core.validators
import django.db.models.deletion
import pgvector.django.vector
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('exam', '0020_alter_studentblacklist_imei'),
        ('region', '0007_alter_swingbarrier_person_count'),
    ]

    operations = [
        migrations.CreateModel(
            name='Supervisor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('last_name', models.CharField(blank=True, max_length=50, verbose_name='Familiya')),
                ('first_name', models.CharField(blank=True, max_length=50, verbose_name='Ism')),
                ('middle_name', models.CharField(blank=True, max_length=50, verbose_name='Sharif')),
                ('imei', models.CharField(db_index=True, max_length=14, unique=True, validators=[django.core.validators.RegexValidator('^\\d{14}$', 'PINFL 14 ta raqamdan iborat')], verbose_name='PINFL')),
                ('ps_ser', models.CharField(max_length=2, validators=[django.core.validators.RegexValidator('^[A-Z]{2}$', 'Faqat 2 ta lotin harfi')], verbose_name='Seriya')),
                ('ps_num', models.CharField(max_length=7, validators=[django.core.validators.RegexValidator('^\\d{7}$', 'Faqat 7 ta raqam')], verbose_name='Nomer')),
                ('img_b64', models.TextField(blank=True, null=True, verbose_name='Rasm')),
                ('img_vector', pgvector.django.vector.VectorField(blank=True, dimensions=512, null=True, verbose_name='Vector')),
                ('gender', models.CharField(choices=[('M', 'Erkak'), ('F', 'Ayol')], default='M', max_length=1, verbose_name='Jinsi')),
                ('status', models.BooleanField(default=True, verbose_name='Aktiv')),
                ('region', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='region.region', verbose_name='Doimiy')),
            ],
            options={
                'verbose_name': 'Nazoratchi',
                'verbose_name_plural': 'Nazoratchilar',
                'db_table': 'supervisor',
            },
        ),
        migrations.CreateModel(
            name='EventSupervisor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category_key', models.CharField(blank=True, max_length=10, null=True, verbose_name='Toifa kodi')),
                ('category_name', models.CharField(blank=True, max_length=50, null=True, verbose_name='Toifa nomi')),
                ('test_date', models.DateField(blank=True, null=True, verbose_name='Test date')),
                ('sm', models.PositiveSmallIntegerField(default=0, verbose_name='Smena')),
                ('group_n', models.PositiveSmallIntegerField(default=0, verbose_name='Guruh')),
                ('access_datetime', models.DateTimeField(verbose_name='Boshlanish vaqti')),
                ('expired_datetime', models.DateTimeField(verbose_name='Tugash vaqti')),
                ('is_participated', models.BooleanField(default=False, verbose_name='Davomat')),
                ('exam', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='exam.exam', verbose_name='Tadbir')),
                ('zone', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='region.zone', verbose_name='Bino')),
                ('supervisor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='supervisor.supervisor', verbose_name='Nazoratchi')),
            ],
            options={
                'verbose_name': 'Biriktirilgan nazoratchi',
                'verbose_name_plural': 'Biriktirilgan nazoratchilar',
                'db_table': 'event_supervisor',
            },
        ),
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('last_name', models.CharField(blank=True, max_length=255, verbose_name='Familiya')),
                ('first_name', models.CharField(blank=True, max_length=255, verbose_name='Ism')),
                ('middle_name', models.CharField(blank=True, max_length=255, verbose_name='Sharif')),
                ('imei', models.CharField(db_index=True, max_length=14, unique=True, validators=[django.core.validators.RegexValidator('^\\d{14}$', 'PINFL 14 ta raqamdan iborat')], verbose_name='PINFL')),
                ('ps_ser', models.CharField(max_length=2, validators=[django.core.validators.RegexValidator('^[A-Za-z]{2}$', 'Faqat 2 ta katta lotin harfi')], verbose_name='Seriya')),
                ('ps_num', models.CharField(max_length=7, validators=[django.core.validators.RegexValidator('^\\d{7}$', 'Faqat 7 ta raqam')], verbose_name='Nomer')),
                ('phone', models.CharField(blank=True, max_length=12, null=True, validators=[django.core.validators.RegexValidator(message="Telefon raqam: '998901234567' formatida bo'lishi kerak", regex='^998\\d{9}$')], verbose_name='Telefon')),
                ('img_b64', models.TextField(blank=True, null=True, verbose_name='Rasm')),
                ('img_vector', pgvector.django.vector.VectorField(blank=True, dimensions=512, null=True, verbose_name='Vector')),
                ('gender', models.CharField(choices=[('M', 'Erkak'), ('F', 'Ayol')], default='M', max_length=1, verbose_name='Jinsi')),
                ('status', models.BooleanField(default=True, verbose_name='Aktiv')),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='region.region', verbose_name='Doimiy viloyat')),
            ],
            options={
                'verbose_name': 'Xodim',
                'verbose_name_plural': 'Xodimlar',
                'db_table': 'staff',
                'indexes': [models.Index(fields=['imei'], name='staff_imei_181f5a_idx')],
                'unique_together': {('ps_ser', 'ps_num')},
            },
        ),
    ]
