# Generated by Django 5.1.6 on 2025-11-28 05:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0023_alter_exam_hash_key'),
        ('region', '0007_alter_swingbarrier_person_count'),
        ('supervisor', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='eventsupervisor',
            unique_together={('supervisor', 'exam', 'zone', 'test_date', 'sm', 'group_n')},
        ),
        migrations.CreateModel(
            name='EventStaff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category_key', models.CharField(blank=True, max_length=10, null=True, verbose_name='Toifa kodi')),
                ('category_name', models.CharField(blank=True, max_length=50, null=True, verbose_name='Toifa nomi')),
                ('test_date', models.DateField(blank=True, null=True, verbose_name='Test date')),
                ('sm', models.PositiveSmallIntegerField(default=0, verbose_name='Smena')),
                ('group_n', models.PositiveSmallIntegerField(default=0, verbose_name='Guruh')),
                ('is_participated', models.BooleanField(default=False, verbose_name='Davomat')),
                ('exam', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='exam.exam', verbose_name='Tadbir')),
                ('staff', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='supervisor.staff', verbose_name='Xodim')),
                ('zone', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='region.zone', verbose_name='Bino')),
            ],
            options={
                'verbose_name': 'Biriktirilgan xodim',
                'verbose_name_plural': 'Biriktirilgan xodimlar',
                'db_table': 'event_staff',
                'unique_together': {('staff', 'exam', 'zone', 'test_date', 'sm', 'group_n')},
            },
        ),
    ]
