# Generated by Django 5.1.6 on 2025-12-01 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supervisor', '0002_alter_eventsupervisor_unique_together_eventstaff'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='staff',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='staff',
            name='region',
        ),
        migrations.AddField(
            model_name='eventsupervisor',
            name='role',
            field=models.CharField(choices=[('staff', 'Xodim'), ('supervisor', 'Nazoratchi'), ('unknown', "Noma'lum")], default='supervisor', max_length=20, verbose_name='Rol'),
        ),
        migrations.DeleteModel(
            name='EventStaff',
        ),
        migrations.DeleteModel(
            name='Staff',
        ),
    ]
