# Generated by Django 5.1.6 on 2025-12-01 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supervisor', '0003_alter_staff_unique_together_remove_staff_region_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eventsupervisor',
            name='role',
        ),
        migrations.AddField(
            model_name='supervisor',
            name='role',
            field=models.CharField(choices=[('staff', 'Xodim'), ('supervisor', 'Nazoratchi'), ('unknown', "Noma'lum")], default='supervisor', max_length=20, verbose_name='Rol'),
        ),
    ]
